import type { Metadata } from "next";
import { Inter,Grand_Hotel } from "next/font/google";
import "./globals.css";
import { PickupLineContext } from "@/context/PickupLinesContext";

const inter = Grand_Hotel({weight: '400', subsets: ["latin","latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
